spring:
  thymeleaf:
  prefix: classpath:/templates/
  suffix: .html
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 179440405929-n0b39vhm90pav6ofpoo55ksmmg6if4it.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true # 주석 처리하여 주석 처리된 상태로 둠
        format_sql: true
        default_batch_fetch_size: 10

jwt:
  issuer: ajufresh@gmail.com
  secret_key: study-springboot